<a href="https://colab.research.google.com/github/guscldns/TestProject/blob/main/0502/19_%EC%8B%9C%EA%B3%84%EC%97%B4%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC_%EC%9C%84%ED%95%9C_%EB%94%A5%EB%9F%AC%EB%8B%9D_RNN%2C_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow import keras # 인공신경망
from sklearn.model_selection import train_test_split

#imdb : 영화 리뷰 데이터 (긍정, 부정)// 많이 사용된 순으로 1위 ~ 500위까지 단어만 가져온다
(train_input, train_target), (test_input, test_target) = keras.datasets.imdb.load_data(num_words = 500)

train_input, val_input, train_traget, val_target = train_test_split(train_input, train_target, test_size=0.2)
# 검증데이터 작성 
# 입력층에 들어갈 데이터는 동일해야 함
# 리뷰 데이터는 사람이 각각 쓴거라 문장이 다 다른데 어떻게 맞춰야 하는가 관건

In [ ]:
train_input[0]
# 숫자 각각이 단어 
# 2 : 500 위 안에 못 든 단어

In [3]:
train_target[0]
# 1이면 긍정. 0이면 부정

1

In [8]:
import numpy as np

box = []

for i in train_input:
    box.append(len(i))

np.mean(box)
# 평균 238개 쓴거 알 수 있음

238.66505

In [2]:
# 텍스트 개수를 맞추는 방법
from tensorflow.keras.preprocessing.sequence import pad_sequences
# keras.utils.to_categorical에서 pad_sequences를 못찾음
# 업데이트로 경로 변경됬다고 해서 앞에 tensorflow 붙여주니 됨

train_seq = pad_sequences(train_input, maxlen = 100)
val_seq = pad_sequences(val_input, maxlen = 100)
# 단어가 적든 많든 무조건 리뷰 안에 있는 단어를 100로 맞춘다.

In [16]:
# 단어가 많으면 앞에서부터 자른다
# 단어가 적으면 0으로 채워서라도 100개를 맞춘다
train_seq.shape

(20000, 100)

In [8]:
train_seq[2]

# 1이라는 단어와 499라는 단어는 동등하나 컴퓨터는 499를 더 중시할 수 있다

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   1,   2,   2,  16,   2,  27,   2,
         2,   2,  11, 289,   2,  50,  26,  49, 478,   2,  21,  12, 152,
       179,   2, 295,   4,   2,   2,  11, 289,   2,   9,   2,   2,  26,
       241,   2,  31,   7,  63,   4,   2,   9, 321], dtype=int32)

In [3]:
# 원핫인코딩 : 해당 숫자만 1이고 나머지가 다 0인 상태로 만들어준다

train_oh = keras.utils.to_categorical(train_seq)
val_oh = keras.utils.to_categorical(val_seq)

In [10]:
train_oh.shape

(20000, 100, 500)

In [11]:
train_oh[1]

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [5]:
val_oh.shape

(5000, 100, 500)

In [6]:
val_oh[1]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [1]:
model = keras.Sequential()
model.add(keras.layers.SimpleRNN(8, input_shape = (100,500)))
# input_shape = (100,500): 맨 처음에 가져올 단어 500개 정해서 뒤의 값 500
# SimpleRNN 대신 LSTM으로 하면 장기기억 가능
model.add(keras.layers.Dense(2, activation = 'softmax'))
# 정답 1아니면 0이라 2개
model.compile(loss='sparse_categorical_crossentropy', metrics = 'accuracy', optimizer='adam')

es = keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)

hist = model.fit(train_oh, train_target, epochs = 10000, validation_data = (val_oh, val_target), callbacks = [es])

NameError: ignored

In [ ]:
import matplotlib.pyplot as plt

plt.plot(hist.history['loss'])
plt.plot(hist.history['val_loss'])

In [1]:
from tensorflow import keras 
from sklearn.model_selection import train_test_split

(train_input, train_target), (test_input, test_target) = keras.datasets.imdb.load_data(num_words = 500)

train_input, val_input, train_traget, val_target = train_test_split(train_input, train_target, test_size=0.2)

from tensorflow.keras.preprocessing.sequence import pad_sequences
# keras.utils.to_categorical에서 pad_sequences를 못찾음
# 업데이트로 경로 변경됬다고 해서 앞에 tensorflow 붙여주니 됨

train_seq = pad_sequences(train_input, maxlen = 100)
val_seq = pad_sequences(val_input, maxlen = 100)

train_oh = keras.utils.to_categorical(train_seq)
val_oh = keras.utils.to_categorical(val_seq)

model = keras.Sequential()
model.add(keras.layers.SimpleRNN(8, input_shape = (100,500)))
model.add(keras.layers.Dense(2, activation = 'softmax'))

model.compile(loss='sparse_categorical_crossentropy', metrics = 'accuracy', optimizer='adam')

es = keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)

hist = model.fit(train_oh, train_target, epochs = 10000, validation_data = (val_oh, val_target), callbacks = [es])

ValueError: ignored