<a href="https://colab.research.google.com/github/guscldns/TestProject/blob/main/0428/10_%ED%8A%B9%EC%84%B1%EA%B3%B5%ED%95%99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

perch = pd.read_csv("perch.csv")
target = perch['weight'].to_numpy() # 정답지, 함수여야 함 / to_numpy() : 함수변환

In [3]:
target

array([   5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
        685. ,  700. ,  700. ,  690. ,  900. ,  650. ,  820. ,  850. ,
        900. , 1015. ,  820. , 1100. , 1000. , 1100. , 1000. , 1000. ])

In [5]:
perch2 = pd.read_csv("perch2.csv") .to_numpy()
perch2

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94],
       [18.  ,  5.22,  3.32],
       [18.7 ,  5.2 ,  3.12],
       [19.  ,  5.64,  3.05],
       [19.6 ,  5.14,  3.04],
       [20.  ,  5.08,  2.77],
       [21.  ,  5.69,  3.56],
       [21.  ,  5.92,  3.31],
       [21.  ,  5.69,  3.67],
       [21.3 ,  6.38,  3.53],
       [22.  ,  6.11,  3.41],
       [22.  ,  5.64,  3.52],
       [22.  ,  6.11,  3.52],
       [22.  ,  5.88,  3.52],
       [22.  ,  5.52,  4.  ],
       [22.5 ,  5.86,  3.62],
       [22.5 ,  6.79,  3.62],
       [22.7 ,  5.95,  3.63],
       [23.  ,  5.22,  3.63],
       [23.5 ,  6.28,  3.72],
       [24.  ,  7.29,  3.72],
       [24.  ,  6.38,  3.82],
       [24.6 ,  6.73,  4.17],
       [25.  ,  6.44,  3.68],
       [25.6 ,  6.56,  4.24],
       [26.5 ,  7.17,  4.14],
       [27.3 ,  8.32,  5.14],
       [27.5 ,  7.17,  4.34],
       [27.5 ,  7.05,  4.34],
       [27

In [10]:
perch2.shape # (56, 3) : 56개 데이터, 3개의 특성

(56, 3)

In [8]:
from sklearn.preprocessing import PolynomialFeatures # 특성공학 가져오는 라이브러리, 대소문자 구분 필수

poly = PolynomialFeatures()
perch_poly = poly.fit_transform(perch2)

In [9]:
perch_poly.shape # 특성이 3>> 10으로 늘어남

(56, 10)

In [12]:
from sklearn.preprocessing import PolynomialFeatures 

poly = PolynomialFeatures(include_bias=False)
# include_bias=False : 편향이라고 1로만 되어 있는 데이터 필요없어서 제외
perch_poly = poly.fit_transform(perch2)
# x1, x2, x3 제곱, x1*x2, x2*x3, x9*x1이 늘어남

In [13]:
# 시험데이터 추가, 순서 중요
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(perch_poly, target)


In [15]:
# 표준화 라이브러리로 사용
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
train_scaled = ss.fit_transform(train_input)
# ss = 표준화 라이브러리
# ss.fit_transform() 에 train_input 값 넣어줌
# train_input의 평균, 표준편차를 학습해서 얻고, 변환해서 train_scaled에 넣어라
test_scaled = ss.transform(test_input)
# ss.transform() : 위에서 구했던 train_input의 평균, 표준편차로 변환해서 test_scaled에 넣어라

In [16]:
test_scaled # 특성이 10개에 표준화가 잘 된 것을 알 수 있음

array([[-0.41605412, -0.58626474, -0.69386454, -0.5444773 , -0.62516942,
        -0.67582816, -0.68613288, -0.72736254, -0.7590987 ],
       [-0.16796259,  0.04509729,  0.10231386, -0.32146331, -0.22171871,
        -0.19169989, -0.13264614, -0.10292631, -0.07773625],
       [-0.68571883, -0.78104664, -0.7265842 , -0.76463619, -0.80299372,
        -0.78152646, -0.82843001, -0.80878397, -0.7822743 ],
       [-0.14638941, -0.30416681, -0.20852291, -0.3011438 , -0.38603691,
        -0.33844519, -0.45625541, -0.41391295, -0.37059004],
       [-1.3652739 , -1.20755184, -1.26645859, -1.2166525 , -1.15371326,
        -1.17069658, -1.09314774, -1.10818623, -1.10966924],
       [-0.73965177, -0.85492943, -0.78111697, -0.80588701, -0.8503932 ,
        -0.82170183, -0.87889423, -0.85333977, -0.82005369],
       [ 1.63339767,  1.445512  ,  1.44381993,  1.88607676,  1.74517057,
         1.75272805,  1.59825057,  1.60539098,  1.58055684],
       [-0.84751766, -0.83813789, -0.75930386, -0.8856077 , -0

In [17]:
import numpy as np
np.mean(train_scaled, axis = 0)
# -4 * e-16(e의-16승) : 0 , e-16,17 다 0

array([-4.89026808e-16, -3.78004506e-16,  8.69674703e-16, -5.55111512e-17,
       -4.22942105e-17, -1.90323947e-16, -3.17206578e-17,  1.21595855e-16,
       -1.45386348e-16])

In [18]:
np.std(train_scaled, axis = 0)
# 표준편차 : 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
from sklearn.linear_model import LinearRegression # 선형회귀 라이브러리

lr = LinearRegression() # 모델생성
lr.fit(train_scaled, train_target) # 학습

LinearRegression()

In [20]:
lr.score(test_scaled, test_target) # 평가
# 특성을 늘렸더니 정확도가 올라간 것을 가능

0.9913841368365901

In [21]:
# 특성을 늘린다고 정확도가 늘어나지 않음
from sklearn.preprocessing import PolynomialFeatures 

poly = PolynomialFeatures(include_bias=False, degree =5 )
# degree =5 : 5 제곱까지 허용
perch_poly = poly.fit_transform(perch2)

In [22]:
perch_poly.shape # 특성 55개로 늘어남

(56, 55)

In [35]:
from sklearn.model_selection import train_test_split # 시험데이터 생성
train_input, test_input, train_target, test_target = train_test_split(perch_poly, target)

In [36]:
from sklearn.preprocessing import StandardScaler # 표준화 라이브러리

ss = StandardScaler()
train_scaled = ss.fit_transform(train_input) # 학습데이터 표준화
test_scaled = ss.transform(test_input) # 시험데이터 표준화

In [37]:
from sklearn.linear_model import LinearRegression # 선형회귀 라이브러리

lr = LinearRegression() # 모델생성
lr.fit(train_scaled, train_target) # 학습
lr.score(test_scaled, test_target) # 평가
# -4 수치 나옴 : 정확도가 -4 라는 뜻 (1 = 100점)
# 너무 모델이 학습세트에 맞아서 선을 이상하게 그을 수 있음 >> 모든 데이터의 정확도 떨어짐
# 과하게 학습 시키면 오히려 역효과

-4.303253554165084