<a href="https://colab.research.google.com/github/guscldns/TestProject/blob/main/0601/0601_07_%E1%84%87%E1%85%AE%E1%86%AB%E1%84%85%E1%85%B2_%E1%84%86%E1%85%A9%E1%84%83%E1%85%A6%E1%86%AF_%E1%84%8B%E1%85%B5%E1%84%92%E1%85%A2(NaiveBayes).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 나이브 베이즈 분류기


In [1]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 71.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 32.9 MB/s eta 0:00:00


In [2]:
# matplotlib 설정
from matplotlib import pyplot as plt
from matplotlib import rc
import numpy as np

%matplotlib inline

# rc('font', family = 'AppleGothic')
# plt.rcParams['axes.unicode_minus'] = False
# # mac OS 에서 한글이 깨진다면 참고.

### 가우시안 나이브 베이즈

- GaussianNB의 경우 연속적인 데이터를 처리하는 용도로 많이 사용된다.  

### 다항 분포, 베르누이 나이브 베이즈

- BernoulliNB, MultinomialNB는 문서분류와 같은 곳에서 많이 사용된다.  

베르누이는 문서에 단어가 출현을 했는지 여부를 따져서 문서를 벡터화 시킨다. 이와 다르게 다항 분포는 단어의 출현횟수를 기록한다.

- 베르누이와 다항분포에는 alpha라는 매개변수가 있다. alpha는 스무딩(smoothing)의 정도를 조절할 수 있다.  
- 그럼 스무딩은 무엇인가? 입력값이 우리가 가지고 있는 훈련데이터에는 없는 값이 들어올 경우 확률이 0이 되어 정상적인 분류가 되지 않는 경우가 생긴다.  
이런 경우를 방지하고자 값을 보정하기 위해 사용되는 기법이 스무딩 기법이다.(라플라스 계산을 사용한다.), 라플라스를 이용하여 특징값이 최소한 한 번은 나타나도록 조정하여 특징값이 0이 될 수 없도록 한다.  
- alpha매개변수는 알고리즘의 성능에 크게 영향을 미치지는 않지만, 값을 조정하면 정확도를 어느정도 높일수는 있다.

In [3]:
from sklearn.naive_bayes import MultinomialNB
# 다항분포: Multinomial, 상황이 여러개일 때 각각의 상황의 확률을 총횟수로 나눠주는 것
# 주사위 던지기 : 다항분포 ↔ 동전던지기
# 베르누이는 이진분류(0/1)일 때 사용, 몇 번 등장했는지 알고 싶으면 다항분포를 사용

In [78]:
from konlpy.tag import Okt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

x_data = ['설문조사하고 백화점 상품권 받아가자',
        '응모권 발급되었어요 응모하시고 천만원 받아가세요', 
        '다음 예약시 할인 가능',
        '피자먹고 유럽투어 가자',
        '블랙프라이데이 한정 세일',
        '머신생명 보험 상담 받으시고 안마의자 받아가세요',
        '회원님 장바구니에 들어있는 제품 할인행사 안내',
        '오늘 아침회의 내용 정리 보고서입니다',
        '5시까지 업무 보고서 제출하세요',
        '이번달 보험료 청구금액은',
        '다음주 일정 확인 부탁드립니다',
         '이번 달 카드 사용 청구서']
y_data = [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]

labels = ['햄', '스팸']


In [79]:
for i, d in enumerate(x_data):
    n_words = Okt().nouns(d) # 명사만 추출
    x_data[i] = ' '.join(n_words)

In [ ]:
x_data

In [6]:
print(n_words)

['이번', '달', '카드', '사용', '청구']


In [35]:
vectorizer = CountVectorizer() # CountVectorizer: 각 문서별로 몇 번 등장했는지 세준다, 다항분포에서 잘 사용
vectorizer.fit(x_data)
x_data = vectorizer.transform(x_data)
print(x_data.shape)

(12, 43)


In [10]:
x_data.toarray() # x_data의 형태

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 

In [20]:
# 분류기의 성능 판단을 위해 train set 분리
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, 
                                                    test_size=0.3, shuffle = True, 
                                                    stratify = y_data)

multi_naive = MultinomialNB().fit(X_train, y_train)

print('train score : {}'.format(multi_naive.score(X_train, y_train)))
print('test score : {}'.format(multi_naive.score(X_test, y_test)))

train score : 1.0
test score : 0.75


In [ ]:
multi_naive.classes_ # 어떠한 클래스가 있는가

array([0, 1])

In [ ]:
multi_naive.class_count_ # 각 클래스 별로 등장 개수

array([4., 4.])

In [ ]:
multi_naive.class_log_prior_
# 사전 확률 분포 로그 값 (베르누이와 다항 분포에서만 사용.)
# = 스팸인지 정상인지의 로그 값

array([-0.69314718, -0.69314718])

In [17]:
new_data = '초특가 할인행사에 괌 여행 응모권까지 받아가자'
n_words = Okt().nouns(new_data)
n_words = ' '.join(n_words)
print(n_words)

초특 할인 행사 괌 여행 응모


In [21]:
n_data = [n_words]
X1 = vectorizer.transform(n_data)
print(X1) # 인덱스로 저장한 값, 1이 행렬의 몇번째에 있는가

  (0, 24)	1
  (0, 38)	1
  (0, 39)	1


In [23]:
X1.toarray() # X1행렬 (25, 39, 40 번째에 있는데 인덱스틑 0부터 시작이라 24,38,39에 있다고 인식)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0]])

In [22]:
model_pred = multi_naive.predict(X1)
print('예측한 값 : {}'.format(model_pred)) 
print('스팸인가?, 아닌가? : {}'.format(labels[model_pred[0]]))

예측한 값 : [1]
스팸인가?, 아닌가? : 스팸


### 실습

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import urllib.request

In [25]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/bab2min/corpus/master/sentiment/steam.txt", filename="steam.txt")

('steam.txt', <http.client.HTTPMessage at 0x7f053f1b4ca0>)

In [38]:
total_data = pd.read_table('steam.txt', names=['label', 'reviews'])
total_data

label                                            reviews
0          0                                          노래가 너무 적음
1          0                    돌겠네 진짜. 황숙아, 어크 공장 그만 돌려라. 죽는다.
2          1                   막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지
3          1               차악!차악!!차악!!! 정말 이래서 왕국을 되찾을 수 있는거야??
4          1                시간 때우기에 좋음.. 도전과제는 50시간이면 다 깰 수 있어요
...      ...                                                ...
99995      0                                       한글화해주면 10개산다
99996      0                                            개쌉노잼 ㅋㅋ
99997      0                             노잼이네요... 30분하고 지웠어요...
99998      1  야생을 사랑하는 사람들을 위한 짧지만 여운이 남는 이야기. 영어는 그리 어렵지 않습니다.
99999      1                     한국의 메탈레이지를 떠오르게한다 진짜 손맛으로 하는게임

[100000 rows x 2 columns]

In [48]:
# 적절하게 벡터화하여 나이브 베이즈 분류모델을 만드세요

total_data['nive'] = total_data['reviews'].str.replace("[^가-힣0-9\.\,]", " ")
total_data

<ipython-input-48-5153feb29852>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  total_data['nive'] = total_data['reviews'].str.replace("[^가-힣0-9\.\,]", " ")


label                                            reviews  \
0          0                                          노래가 너무 적음   
1          0                    돌겠네 진짜. 황숙아, 어크 공장 그만 돌려라. 죽는다.   
2          1                   막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지   
3          1               차악!차악!!차악!!! 정말 이래서 왕국을 되찾을 수 있는거야??   
4          1                시간 때우기에 좋음.. 도전과제는 50시간이면 다 깰 수 있어요   
...      ...                                                ...   
99995      0                                       한글화해주면 10개산다   
99996      0                                            개쌉노잼 ㅋㅋ   
99997      0                             노잼이네요... 30분하고 지웠어요...   
99998      1  야생을 사랑하는 사람들을 위한 짧지만 여운이 남는 이야기. 영어는 그리 어렵지 않습니다.   
99999      1                     한국의 메탈레이지를 떠오르게한다 진짜 손맛으로 하는게임   

                                                    nive  
0                                              노래가 너무 적음  
1                        돌겠네 진짜. 황숙아, 어크 공장 그만 돌려라. 죽는다.  
2                       막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지  
3                   차악 차악  차악    정말 이래서 왕국을 되찾을 수 있는거야    
4                    시간 때우기에 좋음.. 도전과제는 50시간이면 다 깰 수 있어요  
...                                                  ...  
99995                                       한글화해주면 10개산다  
99996                                            개쌉노잼     
99997                             노잼이네요... 30분하고 지웠어요...  
99998  야생을 사랑하는 사람들을 위한 짧지만 여운이 남는 이야기. 영어는 그리 어렵지 않습니다.  
99999                     한국의 메탈레이지를 떠오르게한다 진짜 손맛으로 하는게임  

[100000 rows x 3 columns]

In [49]:
num = 100
test_data = total_data.iloc[:num]
test_data

label                                            reviews  \
0       0                                          노래가 너무 적음   
1       0                    돌겠네 진짜. 황숙아, 어크 공장 그만 돌려라. 죽는다.   
2       1                   막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지   
3       1               차악!차악!!차악!!! 정말 이래서 왕국을 되찾을 수 있는거야??   
4       1                시간 때우기에 좋음.. 도전과제는 50시간이면 다 깰 수 있어요   
..    ...                                                ...   
95      1  예전 테마병원을 생각하고 구입했는데.. 와... 잠깐 한다고 했는데... 오후 6시...   
96      0       사이버 멀미를 느끼고 싶다면 추천 게임 여러가지 해봤지만 이 게임이 처음이다..   
97      1     진짜 ㄹㅇ 꿀잼 게임 이거 하다 보면 시간가는줄 모름 모드까지 깔아서 하면 더 꿀잼   
98      1  찬란히 빛나는 남자의 상징 그 길고 짧은 여정 ..은 개뿔이... 그냥 바바리맨의 ...   
99      1  재밌음. 버그도 없어지고 중세시대 RPG좋아한다면 한번쯤 해볼만함. 처음에 나올때 ...   

                                                 nive  
0                                           노래가 너무 적음  
1                     돌겠네 진짜. 황숙아, 어크 공장 그만 돌려라. 죽는다.  
2                    막노동 체험판 막노동 하는사람인데 장비를 내가 사야돼 뭐지  
3                차악 차악  차악    정말 이래서 왕국을 되찾을 수 있는거야    
4                 시간 때우기에 좋음.. 도전과제는 50시간이면 다 깰 수 있어요  
..                                                ...  
95  예전 테마병원을 생각하고 구입했는데.. 와... 잠깐 한다고 했는데... 오후 6시...  
96       사이버 멀미를 느끼고 싶다면 추천 게임 여러가지 해봤지만 이 게임이 처음이다..  
97     진짜    꿀잼 게임 이거 하다 보면 시간가는줄 모름 모드까지 깔아서 하면 더 꿀잼  
98  찬란히 빛나는 남자의 상징 그 길고 짧은 여정 ..은 개뿔이... 그냥 바바리맨의 ...  
99  재밌음. 버그도 없어지고 중세시대    좋아한다면 한번쯤 해볼만함. 처음에 나올때 ...  

[100 rows x 3 columns]

In [ ]:
# test_data['nive_1'] = test_data['nive'].apply(lambda x:Okt().nouns(x))
# test_data['nive_1']

In [ ]:
a_data = list(test_data['nive'])
a_data

In [87]:
for i, d in enumerate(a_data):
    n_words = Okt().nouns(d) # 명사만 추출
    a_data[i] = ' '.join(n_words)

In [ ]:
a_data

In [89]:
vectorizer = CountVectorizer() # CountVectorizer: 각 문서별로 몇 번 등장했는지 세준다, 다항분포에서 잘 사용
vectorizer.fit(a_data)
b_data = vectorizer.transform(a_data)
print(b_data.shape)

(100, 376)


In [92]:
y_data = test_data['label']
y_data

0     0
1     0
2     1
3     1
4     1
     ..
95    1
96    0
97    1
98    1
99    1
Name: label, Length: 100, dtype: int64

In [107]:
# 분류기의 성능 판단을 위해 train set 분리
X_train, X_test, y_train, y_test = train_test_split(b_data, y_data, 
                                                    test_size=0.3, shuffle = True, 
                                                    stratify = y_data)

multi_naive = MultinomialNB().fit(X_train, y_train)

print('train score : {}'.format(multi_naive.score(X_train, y_train)))
print('test score : {}'.format(multi_naive.score(X_test, y_test)))

train score : 0.9857142857142858
test score : 0.7


In [94]:
multi_naive.classes_ # 어떠한 클래스가 있는가

array([0, 1])

In [95]:
multi_naive.class_count_ # 각 클래스 별로 등장 개수

array([29., 41.])

In [96]:
multi_naive.class_log_prior_
# 사전 확률 분포 로그 값 (베르누이와 다항 분포에서만 사용.)
# = 스팸인지 정상인지의 로그 값

array([-0.88119941, -0.53492318])

In [108]:
from sklearn.linear_model import LogisticRegression 
lg = LogisticRegression().fit(X_train, y_train)

print('train score : {}'.format(lg.score(X_train, y_train)))
print('test score : {}'.format(lg.score(X_test, y_test)))

train score : 0.9857142857142858
test score : 0.6


In [109]:
multi_logistic = LogisticRegression(multi_class='ovr', random_state=0)
multi_logistic.fit(X_train, y_train)

print('train score : {}'.format(multi_logistic.score(X_train, y_train)))
print('test score : {}'.format(multi_logistic.score(X_test, y_test)))

train score : 0.9857142857142858
test score : 0.6


In [110]:
softmax_model = LogisticRegression(multi_class = 'multinomial', solver = 'lbfgs', random_state=0)
softmax_model.fit(X_train, y_train)

print('train score : {}'.format(softmax_model.score(X_train, y_train)))
print('test score : {}'.format(softmax_model.score(X_test, y_test)))

train score : 0.9857142857142858
test score : 0.6666666666666666


In [111]:
from sklearn.svm import SVC
linear_svc = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 

print('train score : {}'.format(linear_svc.score(X_train, y_train)))
print('test score : {}'.format(linear_svc.score(X_test, y_test)))

train score : 0.9571428571428572
test score : 0.5


In [112]:
from sklearn.svm import LinearSVC
linear_svc2 = LinearSVC(C = 1, loss ='hinge').fit(X_train, y_train)

print('train score : {}'.format(linear_svc2.score(X_train, y_train)))
print('test score : {}'.format(linear_svc2.score(X_test, y_test)))

train score : 0.9571428571428572
test score : 0.5


In [113]:
from sklearn.ensemble import VotingClassifier
lr_clf = LogisticRegression(solver='liblinear')
svc_clf = SVC(probability=True)
vo_clf = VotingClassifier( estimators=[('LR',lr_clf),('SVC',svc_clf)] , voting='hard' )
vo_clf.fit(X_train , y_train)

print('train score : {}'.format(vo_clf.score(X_train, y_train)))
print('test score : {}'.format(vo_clf.score(X_test, y_test)))

train score : 0.9857142857142858
test score : 0.6666666666666666


In [114]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(100, max_depth = 1, max_features = 2)
forest.fit(X_train, y_train)

print('train score : {}'.format(vo_clf.score(X_train, y_train)))
print('test score : {}'.format(vo_clf.score(X_test, y_test)))

train score : 0.9857142857142858
test score : 0.6666666666666666
