<a href="https://colab.research.google.com/github/guscldns/TestProject/blob/main/0427/06_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%ED%95%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd

fish = pd.read_csv("fish.csv")
fish # length , weight : 문제지, class : 정답지

length  weight  class
0     25.4   242.0      1
1     26.3   290.0      1
2     26.5   340.0      1
3     29.0   363.0      1
4     29.0   430.0      1
5     29.7   450.0      1
6     29.7   500.0      1
7     30.0   390.0      1
8     30.0   450.0      1
9     30.7   500.0      1
10    31.0   475.0      1
11    31.0   500.0      1
12    31.5   500.0      1
13    32.0   340.0      1
14    32.0   600.0      1
15    32.0   600.0      1
16    33.0   700.0      1
17    33.0   700.0      1
18    33.5   610.0      1
19    33.5   650.0      1
20    34.0   575.0      1
21    34.0   685.0      1
22    34.5   620.0      1
23    35.0   680.0      1
24    35.0   700.0      1
25    35.0   725.0      1
26    35.0   720.0      1
27    36.0   714.0      1
28    36.0   850.0      1
29    37.0  1000.0      1
30    38.5   920.0      1
31    38.5   955.0      1
32    39.5   925.0      1
33    41.0   975.0      1
34    41.0   950.0      1
35     9.8     6.7      0
36    10.5     7.5      0
37    10.6     7.0      0
38    11.0     9.7      0
39    11.2     9.8      0
40    11.3     8.7      0
41    11.8    10.0      0
42    11.8     9.9      0
43    12.0     9.8      0
44    12.2    12.2      0
45    12.4    13.4      0
46    13.0    12.2      0
47    14.3    19.7      0
48    15.0    19.9      0

In [14]:
data = fish[['length','weight']].to_numpy()
data

array([[  25.4,  242. ],
       [  26.3,  290. ],
       [  26.5,  340. ],
       [  29. ,  363. ],
       [  29. ,  430. ],
       [  29.7,  450. ],
       [  29.7,  500. ],
       [  30. ,  390. ],
       [  30. ,  450. ],
       [  30.7,  500. ],
       [  31. ,  475. ],
       [  31. ,  500. ],
       [  31.5,  500. ],
       [  32. ,  340. ],
       [  32. ,  600. ],
       [  32. ,  600. ],
       [  33. ,  700. ],
       [  33. ,  700. ],
       [  33.5,  610. ],
       [  33.5,  650. ],
       [  34. ,  575. ],
       [  34. ,  685. ],
       [  34.5,  620. ],
       [  35. ,  680. ],
       [  35. ,  700. ],
       [  35. ,  725. ],
       [  35. ,  720. ],
       [  36. ,  714. ],
       [  36. ,  850. ],
       [  37. , 1000. ],
       [  38.5,  920. ],
       [  38.5,  955. ],
       [  39.5,  925. ],
       [  41. ,  975. ],
       [  41. ,  950. ],
       [   9.8,    6.7],
       [  10.5,    7.5],
       [  10.6,    7. ],
       [  11. ,    9.7],
       [  11.2,    9.8],


In [15]:
target = fish['class'].to_numpy()
target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [16]:
from sklearn.model_selection import train_test_split #훈련, 시험 데이터 분할 위해 필요
from sklearn.neighbors import KNeighborsClassifier # 이웃 가져옴, 모델, 학습위함

# 훈련문제집, 시험문제집, 훈련정답지, 시험정답지 = train_test_split(문제집, 정답지, test = 비율)
# 위의 순서대로 적어줘야 함, 순서가 중요. 이름은 크게 중요하지 않음
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size = 0.25)
#  test_size = 0.25 는 75 대 25비율인데 이 비율은 기본 값이라 이 비율로 하려면 따로 적지 않아도 됨

knn = KNeighborsClassifier() # 모델 생성
knn.fit(train_input, train_target) # 학습 시 훈련데이터 문제집, 훈련데이터 문제집으로 학습

KNeighborsClassifier()

In [17]:
knn.score(test_input, test_target)
# 시험 문제, 시험 답지로 평가했는데도 1,0 (100점)

1.0

In [18]:
target # 실제값

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [19]:
knn.predict(test_input) # 예측값 >> 실제값과 똑같음 : 평가 1.0 나온 이유

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0])

In [8]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(data, target) 
# 이렇게만 적어도 훈련 75% 시험 25%로 실행 됨